services:
  seam:
    build:
      context: ./
    container_name: seam-dev
    restart: always
    environment:
      LOG_LEVEL: DEBUG
    ports:
      - 8090:8090
    networks:
      - seam_net

networks:
  seam_net:
    driver: bridge
